---
title: "My document"
author: Audrey Colletta
format: html
---

```{r,show_col_types= FALSE}
library(tidyverse)
library(gtsummary)
nlsy_cols <- c("glasses", "eyesight", "sleep_wkdy", "sleep_wknd", 
               "id", "nsibs", "samp", "race_eth", "sex", "region", 
               "income", "res_1980", "res_2002", "age_bir")
nlsy <- read_csv(here::here("data", "raw", "nlsy.csv"), 
                 na = c("-1", "-2", "-3", "-4", "-5", "-998"),
                 skip = 1, col_names = nlsy_cols) |> 
  mutate(region_cat = factor(region, labels = c("Northeast", "North Central", "South", "West")),
         sex_cat = factor(sex, labels = c("Male", "Female")),
         race_eth_cat = factor(race_eth, labels = c("Hispanic", "Black", "Non-Black, Non-Hispanic")),
         eyesight_cat = factor(eyesight, labels = c("Excellent", "Very good", "Good", "Fair", "Poor")),
         glasses_cat = factor(glasses, labels = c("No", "Yes"))) 
```


# Customization of `tbl_summary()`
this is some text
```{r}
#| label: tbl-one
#| tbl-cap: "this is a table"
tbl_summary(
  nlsy,
  by = sex_cat,
  include = c(sex_cat, race_eth_cat, region_cat,
              eyesight_cat, glasses, age_bir))


```



```{r,}
#| label: tbl
#| tbl-cap: "This table slays"

tbl_summary(
  nlsy,
  by = sex_cat,
  include = c(sex_cat, race_eth_cat, region_cat,
              eyesight_cat, glasses, age_bir),
  label = list(
    race_eth_cat ~ "Race/ethnicity",
    region_cat ~ "Region",
    eyesight_cat ~ "Eyesight",
    glasses ~ "Wears glasses",
    age_bir ~ "Age at first birth"
  ),
  missing_text = "Missing")
```

```{r}
#| eval: false
#| echo: false
tbl_summary(
  nlsy,
  by = sex_cat,
  include = c(sex_cat, race_eth_cat, region_cat,
              eyesight_cat, glasses, age_bir))

```
```{r}
mean(nlsy$sleep_wknd, na.rm = TRUE)

```
```{r}
mean_sleep_wknd <- mean(nlsy$sleep_wknd, na.rm = TRUE)

```
The mean # of hours was `r mean_sleep_wknd` 
#will print number in the context of the text

```{r}
#| label: tbl-descr
#| tbl-cap: "Descriptive statistics"
#| output-location: slide
table1 <- tbl_summary(
  nlsy,
  by = sex_cat,
  include = c(sex_cat, race_eth_cat, region_cat,
              eyesight_cat, glasses, age_bir)) |> 
  add_overall(last = TRUE)
table1
```
#median and iqr for age 
```{r}
Tble1 <- inline_text(table1, variable = "age_bir", column = "stat_1")
```

```{r}
#| label: tbl-two
#| tbl-cap: "this is a table"
table2 <- tbl_summary(
  nlsy,
  by = sex_cat,
  include = c(sex_cat, race_eth_cat, region_cat,
              eyesight_cat, glasses, age_bir, sleep_wknd)) |>
add_overall()

```

```{r}
inline_text(table2, variable = "sleep_wknd", column = "stat_0" )
```
The stat is `r inline_text(table2, variable = "sleep_wknd", column = "stat_0" )` stats. 
